name: Activate Unity credentials
on:
  workflow_dispatch:

jobs:
  activation:
    name: Activate Unity credentials
    runs-on: ubuntu-latest
    steps:
      - name: Activate Unity credentials
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: auto
